//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTypes
    {
        public int ProductTypeID { get; set; }
        public string ProductType { get; set; }
        public Nullable<double> ProductTypeCoef { get; set; }
    }
}
